### PR TITLE
Convert text helper to class and Add tests

### PR DESCRIPTION
**Pull request by aykutkardas**
I made minor improvements to the text helper to make it compatible with the rest of the project.

### CODE REVIEW

**Review by omeraplak — APPROVED** [review]

**Review by salihozdemir — APPROVED** [review]

**Comment by mhrrmk** [comment]
kullanıldığı yerleri de güncellemek gerekemez mi?

**Comment by aykutkardas** [comment]
> kullanıldığı yerleri de güncellemek gerekemez mi?

Currently not used anywhere.

**Comment by omeraplak** [comment]
> > kullanıldığı yerleri de güncellemek gerekemez mi?
> 
> Currently not used anywhere.

upss. Thank you @mhrrmk . 
@aykutkardas I think we can delete it since we don't use it.

**Comment by aykutkardas** [comment]
> > > kullanıldığı yerleri de güncellemek gerekemez mi?
> > 
> > 
> > Currently not used anywhere.
> 
> upss. Thank you @mhrrmk .
> @aykutkardas I think we can delete it since we don't use it.

@omeraplak Actually, this is a much better idea. I thought it was there because it will be used later. I can delete it completely.

**Comment by aykutkardas** [comment]
I deleted the unused text helper. @omeraplak

**Review by omeraplak — APPROVED** [review]

**Pull request merged**
